### ISSUE TITLE
Let's set up Coveralls to work properly

### ISSUE THREAD

**Issue by revelt** [zhso/gulp-post#1]
Hi Barry, guys,

As you are probably aware, currently the Coveralls service is not showing the coverage reports:
![screen shot 2017-08-02 at 11 17 45](https://user-images.githubusercontent.com/8344688/28869352-50215d2a-7774-11e7-8ac6-e5b6b330c6bc.png)

This makes users suspicious is this package maintained or not.

Let's fix this!

I checked the `.travis.yml`, it's using `istanbul` directly. Can it be the cause of the problem with Coveralls service?

Personally my trusted setup is the following: use [nyc](https://github.com/istanbuljs/nyc), then call "coverage" task in `package.json` from `.travis.yml`.

## package json:
```json
"scripts": {
    "coverage": "nyc report --reporter=text-lcov | coveralls",
    ...
```

## .travis.yml:
```json
language: node_js
node_js:
  - 'node'
notifications:
  email:
    on_success: never
    on_failure: change
after_success: npm run coverage
```

## PS.
At this occasion, we could [generate](https://github.com/codsen/bitsausage) the bithound config too. It's being reported as missing on BitHound website.

**Comment by zhso** [comment]
copy

**Comment by revelt** [comment]
@zhso what do you mean?

**Comment by zhso** [comment]
done
